name: Build and Push ESP32 Firmware

on:
  push:
    paths:
      - 'esp32_hub1/src/src.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Auto-install Arduino libraries from ino
        run: |
          grep -oP '(?<=#include <)\w+(?=\.h>)' esp32_hub1/src/src.ino | while read lib; do
            echo "Installing: $lib"
            /home/runner/bin/arduino-cli lib install "$lib" || true
          done

      - name: Compile sketch to local build folder
        run: |
          /home/runner/bin/arduino-cli compile \
            --fqbn esp32:esp32:esp32 \
            --output-dir ./esp32_hub1/build \
            esp32_hub1/src

      - name: Move compiled firmware to root
        run: |
          cd esp32_hub1
          if [ -f firmware.bin ]; then
            mv firmware.bin firmware_old.bin
          fi
          cp build/src.ino.bin firmware.bin

      - name: Push firmware.bin to GitHub
        run: |
          git config --global user.email "runner@github.com"
          git config --global user.name "GitHub Runner"
          git add esp32_hub1/firmware.bin esp32_hub1/firmware_old.bin || true
          git commit -m "🤖 Auto: Update compiled firmware"
          git push https://x-access-token:${{ secrets.GH_PUSH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
