name: Build and Push ESP32 Firmware

on:
  push:
    paths:
      - 'esp32_hub1/src/src.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo (with PAT)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PUSH_TOKEN }}

      - name: Extract and install Arduino libraries
        run: |
          echo "Installing Arduino libraries used in src.ino..."
          grep -oP '(?<=#include <)[^>]+(?=>)' esp32_hub1/src/src.ino | while read lib; do
            base=$(basename "$lib" .h)
            /home/runner/bin/arduino-cli lib install "$base" || true
          done

      - name: Compile sketch
        run: |
          /home/runner/bin/arduino-cli compile \
            --fqbn esp32:esp32:esp32 \
            --output-dir ./esp32_hub1/build \
            esp32_hub1/src

      - name: Rename and move firmware
        run: |
          cd esp32_hub1
          if [ -f firmware.bin ]; then
            mv -f firmware.bin firmware_old.bin
          fi
          cp build/src.ino.bin firmware.bin

      - name: Commit and push firmware
        run: |
          git config --global user.name "Auto Firmware Builder"
          git config --global user.email "runner@github.com"
          git add esp32_hub1/firmware*.bin
          git commit -m "🤖 Auto: Update compiled firmware"
          git push https://x-access-token:${{ secrets.GH_PUSH_TOKEN }}@github.com/edzenis/maintainx.git
