name: Build ESP32 Sketch

on:
  push:
    paths:
      - 'esp32_hub1/src/src.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile ESP32 sketch
        run: |
          /home/runner/bin/arduino-cli compile \
            --config-file /home/runner/.arduino15/arduino-cli.yaml \
            --fqbn esp32:esp32:esp32dev \
            --build-path /home/runner/build \
            esp32_hub1/src

      - name: Move compiled firmware to esp32_hub1
        run: |
          cd esp32_hub1

          if [ -f firmware.bin ]; then
            mv firmware.bin firmware_old.bin
          fi

          NEW_BIN=$(find /home/runner/build -name "*.bin" | head -n 1)
          cp "$NEW_BIN" firmware.bin
