name: Build ESP32 Sketch

on:
  push:
    paths:
      - 'esp32_hub1/src/src.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile ESP32 sketch
        run: |
          /home/runner/bin/arduino-cli compile --fqbn esp32:esp32:esp32dev esp32_hub1/src

      - name: Move compiled firmware to esp32_hub1
        run: |
          cd esp32_hub1

          # Rename existing firmware.bin to firmware_old.bin if it exists
          if [ -f firmware.bin ]; then
            mv firmware.bin firmware_old.bin
          fi

          # Find the compiled .bin file
          NEW_BIN=$(find ../ -type f -name "src.ino.ino.bin" | head -n 1)

          # Copy the new binary to firmware.bin
          cp "$NEW_BIN" firmware.bin
