name: Build ESP32 Sketch

on:
  push:
    paths:
      - 'esp32_hub1/src/src.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile ESP32 sketch
        run: |
          export PATH=/home/runner/bin:$PATH
          
          # Manually configure CLI to use known config paths, not temp HOME
          export ARDUINO_DATA_DIR=/home/runner/arduino
          export ARDUINO_USER_DIR=/home/runner/arduino/sketches
          export ARDUINO_CONFIG_DIR=/home/runner/.arduino15
          
          # Force-add board index URL (in case config file is ignored)
          arduino-cli core update-index \
            --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

          # Ensure core is installed (skip if already there)
          arduino-cli core list | grep esp32 || \
            arduino-cli core install esp32:esp32 \
              --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

          # Compile
          arduino-cli compile \
            --fqbn esp32:esp32:esp32dev \
            --build-path /home/runner/build \
            esp32_hub1/src

      - name: Move compiled firmware to esp32_hub1
        run: |
          cd esp32_hub1

          if [ -f firmware.bin ]; then
            mv firmware.bin firmware_old.bin
          fi

          NEW_BIN=$(find /home/runner/build -name "*.bin" | head -n 1)
          cp "$NEW_BIN" firmware.bin
