name: Build ESP32 Sketch

on:
  push:
    paths:
      - 'esp32_hub1/src/src.ino.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32dev sketch.ino
