name: Build ESP32 Sketch

on:
  push:
    paths:
      - 'esp32_hub1/src/src.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto-install Arduino libraries from src.ino
        run: |
          echo "Installing Arduino libraries used in src.ino..."
          LIBS=$(grep -oP '(?<=#include <)[^>]+(?=>)' esp32_hub1/src/src.ino | cut -d. -f1 | sort -u)
          for lib in $LIBS; do
            echo "Installing: $lib"
            /home/runner/bin/arduino-cli lib install "$lib" || true
          done

      - name: Compile sketch
        run: |
          /home/runner/bin/arduino-cli compile \
            --fqbn esp32:esp32:esp32 \
            --output-dir esp32_hub1/build \
            esp32_hub1/src

      - name: Rename final firmware
        run: |
          cd esp32_hub1
          [ -f firmware.bin ] && mv firmware.bin firmware_old.bin
          cp build/src.ino.bin firmware.bin
