name: Build ESP32 Sketch

on:
  push:
    paths:
      - 'esp32_hub1/src/src.ino'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile sketch
        run: |
          /home/runner/bin/arduino-cli compile --fqbn esp32:esp32:esp32 esp32_hub1/src

      - name: Handle firmware
        run: |
          cd esp32_hub1
          if [ -f firmware.bin ]; then
            mv -f firmware.bin firmware_old.bin
          fi
          cp src/build/esp32.esp32.esp32/src.ino.ino.bin firmware.bin
